proc import datafile="E:\0.妇幼\出生队列\天津市母婴出生队列\数据\数据清洗_刘津楠\临床和孕早数据汇总_加更版\儿童随访数据_系统\z_score.sav" dbms=sav out=a replace;
run;
/*根据查体月份分段,留指定月份*/
data b;
set a;
if age_month=0 then Time=1;
if 5.5<age_month<7.5 then Time=2;
if 11.5<age_month<13.5 then Time=3;
if 17.5<age_month<19.5 then Time=4;
if 23.5<age_month<25.5 then Time=5;
if 29.5<age_month<31.5 then Time=6;
if 35.5<age_month<37.5 then Time=7;
if 41.5<age_month<43.5 then Time=8;
if 47.5<age_month<49.5 then Time=9;
if 53.5<age_month<55.5 then Time=10;
if 59.5<age_month<61.5 then Time=11;
if Time=. then delete;
run;
/*删除重复*/
proc sort data=b nodupkey out=time;
by idchild time;
run;
data time1;
set time;
if time=1;
rename height=fheight1;
rename weight=fweight1;
rename zhaz=fzhaz1;
rename zwaz=fzwaz1;
rename zwhz=fzwhz1;
rename zBMI=fzBMI1;
drop age_month time;
run;
data time2;
set time;
if time=2;
rename height=fheight2;
rename weight=fweight2;
rename zhaz=fzhaz2;
rename zwaz=fzwaz2;
rename zwhz=fzwhz2;
rename zBMI=fzBMI2;
drop age_month time;
run;
data time3;
set time;
if time=3;
rename height=fheight3;
rename weight=fweight3;
rename zhaz=fzhaz3;
rename zwaz=fzwaz3;
rename zwhz=fzwhz3;
rename zBMI=fzBMI3;
drop age_month time;
run;
data time4;
set time;
if time=4;
rename height=fheight4;
rename weight=fweight4;
rename zhaz=fzhaz4;
rename zwaz=fzwaz4;
rename zwhz=fzwhz4;
rename zBMI=fzBMI4;
drop age_month time;
run;
data time5;
set time;
if time=5;
rename height=fheight5;
rename weight=fweight5;
rename zhaz=fzhaz5;
rename zwaz=fzwaz5;
rename zwhz=fzwhz5;
rename zBMI=fzBMI5;
drop age_month time;
run;
data zscore;
merge time1-time5;
by idchild;
run;
data zscore1;
set zscore;
if Fzwhz1=. and Fzwhz2=. and Fzwhz3=. and Fzwhz4=. and Fzwhz5=. then delete;
run;
proc means data=zscore1 nmiss;
run;
/*利用2岁weight for length z socre 画图*/
data zwhz1;
set zscore1;
keep IDchild fzwhz1 fzwhz2 fzwhz3 fzwhz4 fzwhz5;
run;
proc sort data=zwhz1;
by IDchild;
run;
/*创建时间变量*/
data zwhz2;
set zwhz1;
T1=0;
T2=6;
T3=12;
T4=18;
T5=24;
run;
/*查看X的最大值和最小值分别为-5.34和5.77*/
proc means data=zwhz2 min max;
var fzwhz1-fzwhz5;
run;
/*进行潜类别轨迹分析-三分类*/
ods graphics on;
PROC TRAJ data=zwhz2 out=of2 outplot=op2 outstat=os2 outest=OE2 CI95M;
ID IDchild;
VAR fzwhz1-fzwhz5;
INDEP T1-T5;
MODEL CNORM;
NGROUPS 3;
ORDER 3 3 3;
MIN -6;
MAX 6;
RUN;
%trajplotnew(op2,os2, 'WLZ vs. Times','Cnorm Model','WLZ','Times');
ods graphics off;
/*导出含有zwhz分组的数据库OF2和bmi1数据库进行合并并导出*/
data OF3;
set OF2(keep=IDchild group);
label group=group3;
rename group=group3;
run;
/*********进行潜类别轨迹分析结果的重绘图*************/
/*****1、进行绘图数据库的整理********/
proc transpose data=OP2 out=OP21;
by T;
var PRED1-PRED3;
run;
data OP21;
set OP21 (keep=T COL1);
rename COL1=pred;
run;
proc transpose data=OP2 out=OP22;
by T;
var L95M1-L95M3;
run;
data OP22;
set OP22 (keep=T COL1);
rename COL1=L95;
run;
proc transpose data=OP2 out=OP23;
by T;
var U95M1-U95M3;
run;
data OP23;
set OP23 (keep=T COL1);
rename COL1=U95;
run;
data OP;
merge OP21 OP22 OP23;
by T;
run;
/*添加group变量，为最终画图数据库*/
data OPP;
set OP;
by T;
if first.T then group=1;
else group+1;
run;

