proc import datafile="E:\0.妇幼\出生队列\天津市母婴出生队列\数据\数据清洗_刘津楠\临床和孕早数据汇总_加更版\儿童随访数据_系统\z_score.sav" dbms=sav out=a replace;
run;
/*根据查体月份分段,留指定月份*/
data b;
set a;
if age_month=0 then Time=1;
if 5.5<age_month<7.5 then Time=2;
if 11.5<age_month<13.5 then Time=3;
if 17.5<age_month<19.5 then Time=4;
if 23.5<age_month<25.5 then Time=5;
if 29.5<age_month<31.5 then Time=6;
if 35.5<age_month<37.5 then Time=7;
if 41.5<age_month<43.5 then Time=8;
if 47.5<age_month<49.5 then Time=9;
if 53.5<age_month<55.5 then Time=10;
if 59.5<age_month<61.5 then Time=11;
if Time=. then delete;
run;
/*删除重复*/
proc sort data=b nodupkey out=time;
by idchild time;
run;
data time1;
set time;
if time=1;
rename height=fheight1;
rename weight=fweight1;
rename zhaz=fzhaz1;
rename zwaz=fzwaz1;
rename zwhz=fzwhz1;
rename zBMI=fzBMI1;
drop age_month time;
run;
data time2;
set time;
if time=2;
rename height=fheight2;
rename weight=fweight2;
rename zhaz=fzhaz2;
rename zwaz=fzwaz2;
rename zwhz=fzwhz2;
rename zBMI=fzBMI2;
drop age_month time;
run;
data time3;
set time;
if time=3;
rename height=fheight3;
rename weight=fweight3;
rename zhaz=fzhaz3;
rename zwaz=fzwaz3;
rename zwhz=fzwhz3;
rename zBMI=fzBMI3;
drop age_month time;
run;
data time4;
set time;
if time=4;
rename height=fheight4;
rename weight=fweight4;
rename zhaz=fzhaz4;
rename zwaz=fzwaz4;
rename zwhz=fzwhz4;
rename zBMI=fzBMI4;
drop age_month time;
run;
data time5;
set time;
if time=5;
rename height=fheight5;
rename weight=fweight5;
rename zhaz=fzhaz5;
rename zwaz=fzwaz5;
rename zwhz=fzwhz5;
rename zBMI=fzBMI5;
drop age_month time;
run;
data zscore;
merge time1-time5;
by idchild;
run;
data zscore1;
set zscore;
if Fzwhz1=. and Fzwhz2=. and Fzwhz3=. and Fzwhz4=. and Fzwhz5=. then delete;
run;
proc means data=zscore1 nmiss;
run;
/*利用2岁weight for length z socre 画图*/
data zwhz1;
set zscore1;
keep IDchild fzwhz1 fzwhz2 fzwhz3 fzwhz4 fzwhz5;
run;
proc sort data=zwhz1;
by IDchild;
run;
/*创建时间变量*/
data zwhz2;
set z
